### ISSUE TITLE
Reconciling to bigger array

### ISSUE THREAD

**Issue by gaggala** [plusnew/plusnew#10]
### Expected behavior and actual behavior.
Updating of an empty smaller array, then the newer one is currently not reconciling.
It throws an exception because it can't get the old Abstract Element
### Steps to reproduce the problem.
Take empty array, push new values in it afterwards
### Specifications like the version of the project or browser version
0.36, on all browsers

**Comment by plusgut** [comment]
fixed out of bounds, 970b8ddf77c3d98a9c630533ad8fc7a3a9d9177c
