### ISSUE TITLE
SVG Support for namespaced attributes

### ISSUE THREAD

**Issue by Reloaded2** [plusnew/plusnew#108]
### Expected behavior and actual behavior.
SVG should be support namespace attributes

### Steps to reproduce the problem.
    {plusnew.createElement(
            'use',
            {
              'xlink:href': `#profileCount`,
              filter: '"url(#background)',
            },
          )}

### Specifications like the version of the project or browser version
"plusnew": "0.6.42",

**Comment by plusgut** [comment]
thanks for reporting, i will take care of that.

**Comment by plusgut** [comment]
is now fixed in https://github.com/plusnew/plusnew/pull/114
