### ISSUE TITLE
conditional rendering

### ISSUE THREAD

**Issue by gaggala** [plusnew/plusnew#3]
When conditional rendering is used, an abstractElement "false" is created, this causes an exception.

**Comment by Hardenberg** [comment]
Do u have an steps to reproduce? or some snippets?

**Comment by plusgut** [comment]
```
const foo = false;
() => <div>{foo && <span>foo</span>}</div>
```

This code currently throws an exception, but should render just an empty <div />, without the foo-span

**Comment by plusgut** [comment]
Should be fixed https://github.com/plusnew/plusnew/commit/a3ef9d55f8418199ead8d51305c822d89ba1cb14

**Comment by plusgut** [comment]
Thanks for noticing, will be fixed soon. I'll write a test for it, https://github.com/plusnew/plusnew/blob/master/src/instances/types/Dom/Instance.ts#L86 should have an insertBefore instead of appendChild.

**Comment by plusgut** [comment]
okay, it finally is fixed.
