### ISSUE TITLE
Dispatch in ChildConstructor

### ISSUE THREAD

**Issue by gaggala** [plusnew/plusnew#73]
### Expected behavior and actual behavior.
When a childcomponent is dispatching a shared store from the parent at the initial render, an exception is thrown
### Steps to reproduce the problem.

  it('dispatch in child constructor', () => {
    const local = store(0, (_state, action: number) => action);

    const ChildComponent = component(
      'ChildComponent',
      () => {
        local.dispatch(1);
        return { local };
      },
      (props: { value: number }) => {
        return <div>{props.value}</div>
      }
    );

    const MainComponent = component(
      'MainComponent',
      () => {
        return { local };
      },
      () => {
        return <ChildComponent value={local.state} />
      }
    );

    plusnew.render(<MainComponent />, container);

    expect(container.childNodes.length).toBe(1);
    expect((container.childNodes[0] as Element).tagName).toBe('DIV');
    expect((container.childNodes[0] as Element).innerHTML).toBe('1');
  });
### Specifications like the version of the project or browser version
plusnew 0.5.104, all browsers

**Comment by plusgut** [comment]
with registerLifcycleHook that is fixed
