### ISSUE TITLE
value attribute on HTML form elements for browser inspector view

### ISSUE THREAD

**Issue by gaggala** [plusnew/plusnew#8]
### Expected behavior and actual behavior.
for debugging, it would be helpful to have attributes on elements (and not just the property-values)
Currently: it sets the property correctly, but HTMLElement.prototype.setAttribute is not called

### Steps to reproduce the problem.
`<input value="foo" />`

### Specifications like the version of the project or browser version
<0.5.33, tested in chrome and ff

**Comment by plusgut** [comment]
fixed in #33
