### ISSUE TITLE
Undefined in jsx throws unclear exception

### ISSUE THREAD

**Issue by gaggala** [plusnew/plusnew#9]
### Expected behavior and actual behavior.
throws a meaningless exception, it either should throw a meaningful exception, or display an empty string, or act as an placeholder
### Steps to reproduce the problem.
`render: () => undefined`
### Specifications like the version of the project or browser version
0.5.34, in all browsers

**Comment by plusgut** [comment]
fixed https://github.com/plusnew/plusnew/commit/dd271fedc3f029c64db4b0509ffdf518355404ff https://github.com/plusnew/plusnew/commit/1e00803d077a56e381b9518b96c19e0db739db77
